# Site settings
title: Fried Notes
description: Practical guides, release notes, and API references.
url: "https://venkat4real.github.io"
baseurl: "/FriedNotes"
lang: en

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs

exclude:
  - readme.md
